// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lepzxhvuodrfqjfhrbvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxlcHp4aHZ1b2RyZnFqZmhyYnZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NDk2MzgsImV4cCI6MjA3NDUyNTYzOH0.vQfPZ1QJc7WlPXAWyZTtCelRzE_viaVcWvWZgaCUJKk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});